
# Generated by Qodo Gen

from testarea.pip_get_list import install_package

# Dependencies:
# pip install pytest-mock
import pytest

class TestInstallPackage:

    # Successfully installs a package using pip3
    def test_successfully_installs_package(self, mocker):
        # Arrange
        mock_run = mocker.patch('subprocess.run')
        package_name = "pip"
    
        # Act
        install_package(package_name)
    
        # Assert
        mock_run.assert_called_once_with(
            ["pip3", "install", "--upgrade", package_name], 
            check=True
        )

    # Package name is empty string
    def test_installs_with_empty_package_name(self, mocker):
        # Arrange
        mock_run = mocker.patch('subprocess.run')
        package_name = ""
    
        # Act
        install_package(package_name)
    
        # Assert
        mock_run.assert_called_once_with(
            ["pip3", "install", "--upgrade", ""], 
            check=True
        )